### ISSUE TITLE
[FEATURE REQUEST] Zone ID Check

### ISSUE THREAD

**Issue by kgetit** [PrincessRTFM/TinyCommands#3]
WOW, you move quick! Love the mount, flying, swimming, etc additions!! Now you just made it so I can't live without this plugin. So, another request and you can tell me if I'm asking for too much. But, can you add a zone condition towards the IDs? Example:

/ifcmd -z 250 /pvpac "Drill"
/ifcmd -Z 250 /ac "Drill"

250 = Wolf's Den Pier (I'm just using this and above as an example. I'm sure you know all the zones). With a zone ID check there can be some cool and space saving macros. THANKS AGAIN for this lovely plugin! 🥇 👍

**Comment by PrincessRTFM** [comment]
Hmm... the main issue with this is that the command parser I wrote doesn't support providing values to the flags. That's actually why the `/ifjob` command had to be separate, I couldn't include `-j`/`-J` for jobs with a provided value.

So, there's two options I can see here: one is that this goes on hold until I can eventually hack together a new command parser that can handle flags with values, which will be... a while. The other is that I add this as a _new_ command, probably `/ifzone` with a few aliases, in which case it'll be a lot faster. Since it sounds like you're really liking the macro improvements of this plugin, I'll go with the second and put the first on my todo list for Someday:tm:.

Just a word of warning, be careful making your macros _too_ adaptable in case people start thinking you're botting!

**Comment by kgetit** [comment]
Heh, warning noted. This plugin condensed my macros by  25-30%. You rock! I'm just dreading the 6.08 update when nothing works for a bit. ::cring::

**Comment by kgetit** [comment]
Just want to add a working macro with your creation:

`/ifzone -N 813,814,815,816,817,818,956,957,958,959 /levelsync on
/mount "Black Chocobo"'

This will only activate levelsync for SB zones in EW zones that needs a sync when I click the mount key for doing Shared FATES farming . Since I also do Treasure Hunts and you know that certain spots are right on top of FATES at lower levels, your plugin becomes insanely useful. 🥇
