### ISSUE TITLE
[FEATURE REQUEST] Spell cooldown and/or target distance check

### ISSUE THREAD

**Issue by Meepster99** [PrincessRTFM/TinyCommands#6]
I absolutely love what this plugin has allowed me to do. 
I was wondering if it would be possible to integrate a command which checks if a spell is on cooldown, and maybe one for checking the distance to target to make sure it is castable?

**Comment by PrincessRTFM** [comment]
If you're planning on using this for combat macros, I have to _strongly_ recommend against it, since macros in combat cannot make use of action queueing. You may be interested in various XIVCombo forks ([including mine!](https://github.com/PrincessRTFM/XIVComboPlugin)) and things like MoAction, ReAction, or Redirect.

That aside, [TinyCommands will no longer be receiving new conditional commands, and existing ones are to be considered deprecated](https://github.com/PrincessRTFM/TinyCommands/discussions/5). They may be removed in the future. The new method for doing such things is [WoLua](https://github.com/PrincessRTFM/WoLua), to write fully custom scripted chat commands in the lua scripting language.

At present, WoLua doesn't have means to do this, but I can put it on the todo list if you [open an issue there](https://github.com/PrincessRTFM/WoLua/issues/new/choose) to remind me.
