### ISSUE TITLE
Game crashing randomly in combat

### ISSUE THREAD

**Issue by HimitsuYami** [PrincessRTFM/TinyCommands#9]
My game has been randomly crashing while in combat lately and after some troubleshooting, after removing this plugin after getting some help from the Dalamud Discord in tracking it down, my game stopped crashing so I can only assume it was this plugin. Couldn't really find much cause of when it happened but here's the log file from said crash (in a .zip because github doesn't like the format it came in). I wasn't actively even using any features for it (and so will just leave it uninstalled for now) but that's the info I have. It was crashing fairly consistently in PotD and Eureka Orthos while installed though.
[crash-20230316141513.zip](https://github.com/PrincessRTFM/TinyCommands/files/10995558/crash-20230316141513.zip)

**Comment by PrincessRTFM** [comment]
I don't even know what a `.tspack` file _is_, never mind how you got one from what should be a _plaintext_ log file. I'm also not sure how TC is crashing, especially at random and without you using any of the commands, since it doesn't try to do anything unless you use one of the commands.

I found what looks like your messages in the server, and there's nothing specifically about TC. What other third-party plugins did you have active?

**Comment by HimitsuYami** [comment]
There are a lot but after disabling only this one it fixed. The `.tspack` is the file I got from the "click here" link Dalamud gave me when the game crashed

**Comment by PrincessRTFM** [comment]
It may have been fixed because of a broken interaction with another plugin. Also, it turns out that `.tspack` is just the name the Dalamud devs chose to use for a standard zip file to indicate its purpose, so lemme take a look.

**Comment by PrincessRTFM** [comment]
Yeah, that's not TC. You're getting an access violation error in code modifying item tooltips, which TC doesn't touch at all. There's nothing I can do about that.
